// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package domain is a generated GoMock package.
package domain

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserResourceItf is a mock of UserResourceItf interface
type MockUserResourceItf struct {
	ctrl     *gomock.Controller
	recorder *MockUserResourceItfMockRecorder
}

// MockUserResourceItfMockRecorder is the mock recorder for MockUserResourceItf
type MockUserResourceItfMockRecorder struct {
	mock *MockUserResourceItf
}

// NewMockUserResourceItf creates a new mock instance
func NewMockUserResourceItf(ctrl *gomock.Controller) *MockUserResourceItf {
	mock := &MockUserResourceItf{ctrl: ctrl}
	mock.recorder = &MockUserResourceItfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserResourceItf) EXPECT() *MockUserResourceItfMockRecorder {
	return m.recorder
}

// FindUser mocks base method
func (m *MockUserResourceItf) FindUser(arg0 int) error {
	ret := m.ctrl.Call(m, "FindUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindUser indicates an expected call of FindUser
func (mr *MockUserResourceItfMockRecorder) FindUser(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockUserResourceItf)(nil).FindUser), arg0)
}
